//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosaic.MOL.API.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://aldsapxd2.mosaicco.com:50000/XISOAPAdapter/MessageServlet? CC_SOAP_BRAZILM" +
            "O=:BSYS_MOL_IIS_D:CC_SOAP_BRAZILMO&version=3.0&Sender.Service=BSYS_MOL_IIS_D&Int" +
            "erface=http%3A%2F%2Fmosaicco.com%2FMosaicBrazil%5ESI_CREATE_CONTRACT_OB_BrazilMO" +
            "")]
        public string Mosaic_MOL_API_Web_CreateContractService_SI_CREATE_CONTRACT_OB_BrazilMOService {
            get {
                return ((string)(this["Mosaic_MOL_API_Web_CreateContractService_SI_CREATE_CONTRACT_OB_BrazilMOService"]));
            }
        }
    }
}
